spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates

server:
  port: 9090

app:
  base:
    url: http://localhost:${server.port}/
  chat:
    url: ${app.base.url}index?username=%s
  websocket:
    url: ws://localhost:${server.port}/chat/

selenium:
  chromedriver: C:\chromedriver_win64\chromedriver.exe